*** empty log message ***

diff --git a/gcl-fe b/gcl-fe
--- a/gcl-fe
+++ b/gcl-fe
@@ -1,104 +1,157 @@
-#!/bin/sh
+#! /bin/sh
+# gcl-fe --- front end driver for multiple installations of GCL
+
+# Copyright (C) 1996 Noah S. Friedman
+
+# $Id$
+
+# This program is free software; you can redistribute it and/or modify
+# it under the terms of the GNU General Public License as published by
+# the Free Software Foundation; either version 2, or (at your option)
+# any later version.
+#
+# This program is distributed in the hope that it will be useful,
+# but WITHOUT ANY WARRANTY; without even the implied warranty of
+# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+# GNU General Public License for more details.
+#
+# You should have received a copy of the GNU General Public License
+# along with this program; if not, you can either send email to this
+# program's maintainer or write to: The Free Software Foundation,
+# Inc.; 59 Temple Place, Suite 330; Boston, MA 02111-1307, USA.
+
+# Commentary:
+
+# Inspired by a similar, earlier script by Charles Sandel <sandel@cli.com>
 
 # Front-end shell script for GNU GCL, used to
 # manage multiple versions of GCL.
-#
-# Strategy: Install this script as "$GNUTOP/bin/gcl" .  This is what
-# users should normally execute to run "gcl" .
+
+# Strategy: Install this script as "$prefix/bin/gcl".
+# This is what users should normally execute to run "gcl".
+
 # Give each version of GCL a separate hierarchy under
-# $GCLTOP, with the name "gcl-NN.NN" where NN.NN is the version number.
+# "$prefix/lib", with the name "gcl-NN.NN" where NN.NN is the version number.
 # This script looks at what versions are available, and selects a version,
-# currently $OLDEST .  However,
-# users can specify their own choice to force the selection of a
-# particular version by setting the environment
-# variable GCLVERSION to have a value which is the version number of the
-# GCL that they want to use (just the numeric value),
-# or to specify either the NEWEST or OLDEST
+# currently $DEFAULTVERSION.
+
+# However, users can specify their own choice to force the selection of a
+# particular version by setting the environment variable GCLVERSION to have
+# a value which is the version number of the GCL that they want to use
+# (just the numeric value), or to specify either the NEWEST or OLDEST
 # versions.
-#
 
-PROGNAME=`basename $0`	# name of this program
-if [ "$GCLTOP" = "" ] ; then
-	GCLTOP=/cli/project/gcl	# root of the GCL installed tree
-fi
-if [ "$GPREFIX" = "" ] ; then
-	GPREFIX="gcl-"	# prefix name of the top
-				# of all GCL hierarchies
+# Code:
+
+# Name by which this script was invoked.
+progname=`echo "$0" | sed -e 's/[^\/]*\///g'`
+
+# To prevent hairy quoting and escaping later.
+bq='`'
+eq="'"
+
+DEFAULTVERSION="${DEFAULTVERSION-NEWEST}"
+
+if [ "$prefix" = "" ] ; then
+  # root of the GNU installed tree
+  prefix=/usr/local/gnu
 fi
 
-if [ ! -d $GCLTOP ] ; then
-	echo "Cannot find root of GCL tree."
-	exit 1
+if [ ! -d "$prefix" ] ; then
+  echo "Cannot find root of GNU tree ($prefix)."
+  exit 1
 fi
+
+gclprefix="$prefix/lib/gcl-"
 
 # Find out which versions are available on the system and sort them
-# in numeric order
-AVAILVERSIONS=`ls -1d $GCLTOP/$GPREFIX*/unixport/saved_$PROGNAME 2>&1 | \
-	egrep -i -v 'no match|no such|not found' | \
-	sed -e "s;$GCLTOP/$GPREFIX;;g" -e "s;/unixport/saved_$PROGNAME;;g" | \
-	awk -F. '{printf "%d.%03d\n", $1, $2}' |
-	sort -n | \
-	awk -F. '{printf "%d.%d\n", $1, $2}'`
+# in numeric order.
+#
+# The largish sed script prefixes all version numbers with a sort key.
+# That key is constructed by padding out any single or double digits to 3
+# digits from the version number, then converting all occurences of `.' to
+# `0', and prefixing and suffixing the entire result with an additional
+# zero.  After sorting, the sort key is stripped from the output.
+# We do all this because `sort' cannot numerically sort decimal numbers and
+# will stop on the first `.'.
+# This may not work correctly if the version number has more than 4 levels
+# of minor versions (e.g. "1.2.3.4.5" may cause problems).
 
-if [ "$AVAILVERSIONS" = "" ] ; then
-	echo "No version of $PROGNAME found in $GCLTOP."
+
+availversions=`ls -1d $gclprefix*/unixport/saved_gcl 2> /dev/null \
+                | sed -n \
+                      -e "s#^$gclprefix\([0-9.][0-9.]*\)/unixport.*#\1#" \
+                      -e 'h
+                          s/[^.]*[^0-9.][^.]*\.//g
+                          :0
+                          /[0-9.][0-9.]*\.[0-9.][0-9.]*\.[0-9.][0-9.]*\.[0-9.][0-9.]*/!{
+                            s/$/.0/
+                            b 0
+                          }
+                          s/^/./
+                          s/$/./
+                          :1
+                          s/\.\([0-9]\)\./.00\1./g
+                          s/\.\([0-9][0-9]\)\./.0\1./g
+                          t 1
+                          s/\./0/g
+                          G
+                          s/\n/ /' \
+                       -e 'p' \
+                 | sort -nu \
+                 | sed -e 's/.* //'`
+
+if [ "$availversions" = "" ] ; then
+	echo "No version of gcl found in $prefix."
 	exit 1
 fi
 
-OLDEST=`echo "$AVAILVERSIONS" | tr ' ' '\012' | head -1`
-NEWEST=`echo "$AVAILVERSIONS" | tr ' ' '\012' | tail -1`
+# This sets `oldest' to the oldest version available, and `newest'
+# to the newest version available.
+# On line 1, we save the original pattern in the hold space and restore it
+# in case it is the only line of input.
+eval `echo "$availversions" \
+       | sed -ne '1{h;s/^/oldest=/p;g;}
+                  ${s/^/newest=/p;}
+                 '`
 
-# The environment variable GCLVERSION can have a value which specifies
-# a version number, OR it can contain the values "NEWEST" or "OLDEST" to
-# specify the newest or oldest version which was found.
-#
-# This next line makes GCLVERSION be case-insensitive
-#GCLVERSION=`echo "$GCLVERSION" | tr '[a-z]' '[A-Z]'`
-#
-case "$GCLVERSION" in
-	OLDEST)
-		GCLVERSION="$OLDEST"
-		;;
-	NEWEST)
-		GCLVERSION="$NEWEST"
-		;;
-	"")
-		GCLVERSION="$OLDEST"
-		;;
-	*)
-		if [ ! -d $GCLTOP/$GPREFIX$GCLVERSION ] ;  then
-			echo "Cannot find requested version $GCLVERSION."
-			unset GCLVERSION	# so the error message
-						# below will be used
-		fi
-		;;
+version="${GCLVERSION-$DEFAULTVERSION}"
+
+case "$version" in
+  [Oo][Ll][Dd][Ee][Ss][Tt]) version="$oldest" ;;
+  [Nn][Ee][Ww][Ee][Ss][Tt]) version="$newest" ;;
+  '') version="$oldest" ;;
+  *)
+    if [ ! -d "$gclprefix$version" ] ;  then
+      echo "$progname: $version: Cannot find requested version." 1>&2
+      version=
+    fi
+   ;;
 esac
 
-# If we don't have a value by now for GCLVERSION, then give up.
-if [ "$GCLVERSION" = "" ] ; then
-	echo "Cannot determine which $PROGNAME version to use."
-	echo -n "Available versions are: "
-	echo $AVAILVERSIONS
-	exit 1
+# If we don't have a version by now, then give up.
+if [ "$version" = "" ] ; then
+  exec 1>&2
+  echo "$progname: Cannot determine which version to use."
+  case "$availversions" in
+    */* )
+      echo "Available versions are:"
+      for f in $availversions; do
+        echo "   $f"
+      done | sort
+     ;;
+    * )
+      echo "Available versions are:" $availversions
+     ;;
+  esac
+  exit 1
 fi
 
-# Set up the MANPATH so that the man pages for this version
-# are searched first
-if [ -d $GCLTOP/$GPREFIX$GCLVERSION/man ] ; then
-	MANPATH=$GCLTOP/$GPREFIX$GCLVERSION/man:$MANPATH
-	export MANPATH
-fi
-
-if [ -f $GCLTOP/$GPREFIX$GCLVERSION/unixport/saved_$PROGNAME ] ; then
-	PATH=$GCLTOP/$GPREFIX$GCLVERSION/unixport:$PATH
-	export PATH
-#####	exec $PROGNAME $*
-	exec $GCLTOP/$GPREFIX$GCLVERSION/unixport/saved_$PROGNAME -dir $GCLTOP/$GPREFIX$GCLVERSION/unixport/ $@
-else
-	echo "Cannot find $GCLTOP/$GPREFIX$GCLVERSION/unixport/saved_$PROGNAME"
-	exit 1
-fi
-
-# If we get here then we have real problems.  Give up.
-echo "Exec failure on $GCLTOP/$GPREFIX$GCLVERSION/unixport/saved_$PROGNAME"
-exit 1
+libdir=$gclprefix$version
+exec "$libdir/unixport/saved_gcl" \
+   -dir "$libdir/unixport/" \
+   -libdir "$libdir/" \
+   -eval '(setq si::*allow-gzipped-file* t)' \
+   -eval '(setq si::*tk-library* "/usr/lib/tk")' \
+   ${1+"$@"}
+# other options: -load /tmp/foo.o -load jo.lsp -eval "(joe 3)"
