Do not rely on exit status of {nis,yp}match.

diff --git a/match b/match
--- a/match
+++ b/match
@@ -4,7 +4,7 @@
 # Created: 1993-02-03
 # Public domain.
 
-# $Id: match,v 1.2 1995/09/23 20:25:27 friedman Exp friedman $
+# $Id: match,v 1.3 1995/09/23 22:02:47 friedman Exp friedman $
 
 # Commentary:
 
@@ -95,12 +95,24 @@ case "$dbase" in
 esac
 
 # First try NIS; if the record is there, quit.
-if { nismatch "$name" "$dbase" \
-     || ypmatch "$name" "$dbase"
-   } 2> /dev/null
-then
-  exit $?
-fi
+# We can't depend on the exit status of nismatch or ypmatch.
+# On i386-*-bsdi2.0, for example, ypmatch does not exit with an error
+# condition if yp is not in use.
+#
+# if { nismatch "$name" "$dbase" \
+#      || ypmatch "$name" "$dbase"
+#    } 2> /dev/null
+# then
+#   exit $?
+# fi
+str=`{ nismatch "$name" "$dbase" || ypmatch "$name" "$dbase"; } 2> /dev/null`
+case "$str" in
+  '' ) : ;;
+  *  )
+    echo "$str"
+    exit 0
+   ;;
+esac
 
 # First determine regexp to use
 case "$dbase" in
