Renamed to `pstoany'.
Handle any output format supported by gs.

getopt: Handle single-letter options with optional args better.

-a (--antialias): New option.
Generate {Text,Graphics}Alphabit settings for gs when invoked.

-s, -X, -Y (--size, --x-size, --y-size): New options.
Handle proper scaling to preserve aspect ratio.

Do not allow --output-file to be specified if more than one input file
given on command line.

diff --git a/pstoany b/pstoany
--- a/pstoany
+++ b/pstoany
@@ -1,12 +1,12 @@
 #! /bin/sh
-# pstogif --- convert PostScript images to GIF
+# pstoany --- convert PostScript images to gif, jpeg, etc.
 
-# Copyright (C) 1995 Noah S. Friedman
+# Copyright (C) 1994, 1995, 1998 Noah S. Friedman
 
-# Author: Noah Friedman <friedman@prep.ai.mit.edu>
+# Author: Noah Friedman <friedman@splode.com>
 # Created: 1994-10-17
 
-# $Id: pstogif,v 1.5 1995/11/13 23:06:10 friedman Exp $
+# $Id$
 
 # This program is free software; you can redistribute it and/or modify
 # it under the terms of the GNU General Public License as published by
@@ -25,16 +25,17 @@
 
 # Commentary:
 
-# This program uses Ghostscript to convert postscript files to gif format.
-# If ghostscript was not installed with support for writing gif-format
-# files directly, other intermediary formats can be used instead, such as
-# ppm, pgm, pbm, etc.  In that case, the `pbmplus' or `netpbm' utilities
-# need to be in your path so this program can access them.
+# This program uses Ghostscript to convert postscript files to gif, jpeg,
+# png, etc.  Because of patent problems, modern versions of Ghostscript do
+# not have support for writing gif-format files directly.  If support is
+# missing, ghostscript is used to convert the image to ppm format and the
+# external `ppmtogif' program is used to finish the conversion.  The
+# ppmtogif program can be found in the `pbmplus' or `netpbm' packages.
 
 # Code:
 
 # This string is expanded by RCS automatically when this file is checked out.
-rcs_revision='$Revision: 1.5 $'
+rcs_revision='$Revision: 1.6 $'
 
 # Name by which this script was invoked.
 progname=`echo "$0" | sed -e 's/[^\/]*\///g'`
@@ -45,14 +46,20 @@ eq="'"
 
 # normal font resolution in dots per inch
 defres=72
-xres=$defres
-yres=$defres
+xres=
+yres=
 
 # Magnification step
 xmag=1
 ymag=1
 
+# Image size
+xsize=
+ysize=
+
+ppmtogifp=
 format=gif8
+aliasbits=0
 
 GS="${GS-gs}"
 
@@ -61,34 +68,53 @@ revision=`set fnord $rcs_revision; echo $3`
 usage="Usage: $progname {options} file1.ps {file2.ps {...}}
 (Version $revision)
 
-Options are:
+Diagnostic options:
 -D, --debug                  Turn on shell debugging ($bq${bq}set -x$eq$eq).
                              Implies --verbose.
--f, --force                  Overwrite existing .gif or other intermediary
+-h, --help                   You're looking at it.
+-q, --quiet                  Do not report progress during conversion.
+-v, --verbose                Report progress.  This is the default.
+-V, --version                Show version number of this program & exit.
+
+File options:
+-F, --force                  Overwrite existing .gif or other intermediary
                              format files without notification.  By
                              default, this program refuses to overwrite any
                              existing files.
--h, --help                   You're looking at it.
--i, --intermediary-format    Specify FMT as the ${bq}device$eq (i.e. output
-                      FMT    format) for Ghostscript.  Currently recognized
-                             formats include: gif8 gifmono ppm ppmraw
-                             The default is $bq$format$eq.
--m, --magnify         STEP   Magnify x and y sizes by a factor of STEP.
-                             Default is xmag=$xmag, ymag=$ymag
+-f, --format          FMT    Specify FMT as the ${bq}device$eq (i.e. output
+                             format) for Ghostscript.  Default is $bq$format$eq.
 -o, --output-file     FILE   Use FILE as the output file name.
                              This is only appropriate when used with a
                              single input file to convert.
--q, --quiet                  Do not report progress during conversion.
+
+Image scaling and dithering options:
+-a, --antialias       BITS   Use BITS bits of alpha antialiasing.
+                             Valid values are 1 (no aliasing), 2, or 4.
+                             Argument is optional and defaults to 4.
+                             See ${bq}language.txt$eq in ghostscript sources.
+
+-m, --magnify         STEP   Magnify x and y sizes by a factor of STEP.
+                             Default is xmag=$xmag, ymag=$ymag
+-x, --x-magnification XSTEP  Like $bq--magnify$eq, but only change x factor.
+-y, --y-magnification YSTEP  Like $bq--magnify$eq, but only change y factor.
+
+-s, --size            WxH    Resize image to W by H pixels.
+                             To preserve aspect ratio automatically, use
+                             $bq--x-size$eq or $bq--y-size$eq to specify
+                             the size of just one axis.
+-X, --x-size          XSIZE  Resize image to XSIZE pixels horizontal.
+                             Aspect ratio is preserved unless $bq--y-size$eq
+                             is also specified.
+-Y, --y-size          YSIZE  Resize image to YSIZE pixels veritcal.
+                             Aspect ratio is preserved unless $bq--x-size$eq
+                             is also specified.
+
 -r, --resolution      RES    Input image resolution for both x and y
                              coordinates, in dots per inch.  You probably
-                             never need to adjust this.
-                             Default is xres=$xres, yres=$yres
--V, --version                Show version number of this program & exit.
--v, --verbose                Report progress.  This is the default.
--X, --x-resolution    XRES   Like $bq--resolution$eq, but only change x value.
--x, --x-magnification XSTEP  Like $bq--magnify$eq, but only change x factor.
--Y, --y-resolution    YRES   Like $bq--resolution$eq, but only change y value.
--y, --y-magnification YSTEP  Like $bq--magnify$eq, but only change y factor.
+                             never need to adjust this manually.
+                             Default is xres=$defres, yres=$defres
+    --x-resolution    XRES   Like $bq--resolution$eq, but only change x value.
+    --y-resolution    YRES   Like $bq--resolution$eq, but only change y value.
 "
 
 # Usage: eval "$getopt"; value=$optarg
@@ -101,8 +127,10 @@ Options are:
 # after every call to getopt.  The argument (if any) is stored in the
 # variable `optarg'.
 #
-# Long option syntax is `--foo=bar' or `--foo bar'.  2nd argument
-# won't get used if first long option syntax was used.
+# Long option syntax is `--foo=bar' or `--foo bar'.
+# For optional args, you must use the `--foo=bar' long option syntax
+# if the argument starts with `-', otherwise the argument will be ignored
+# and treated as the next option.
 #
 # Note: because of broken bourne shells, using --foo=bar syntax can
 # actually screw the quoting of args that end with trailing newlines.
@@ -112,33 +140,28 @@ getopt='
   {
     optarg=
     case "$1" in
-      --*=* )
-        optarg=`echo "$1" | sed -e "1s/^[^=]*=//"`
-        shift
-       ;;
-      * )
-        case ${2+set} in
-          set )
-            optarg="$2"
-            shift
-            shift
+      --*=* ) optarg=`echo "$1" | sed -e "1s/^[^=]*=//"` ; shift ;;
+      -* )
+        case "${2+set}:$optarg_optional" in
+          set: ) optarg="$2" ; shift ; shift ;;
+          set:?* )
+            case "$2" in
+              -* ) shift ;;
+              * )  optarg="$2"; shift; shift ;;
+            esac
            ;;
-          * )
-            case "$optarg_optional" in
-              "" )
-                case "$1" in
-                  --*=* ) option=`echo "$1" | sed -e "1s/=.*//;q"` ;;
-                  * ) option="$1" ;;
-                esac
-                exec 1>&2
-                echo "$progname: option $bq$option$eq requires argument."
-                echo "$progname: use $bq--help$eq to list option syntax."
-                exit 1
-               ;;
-           esac
-         ;;
+          : )
+            option="$1"
+            case "$option" in
+              --*=* ) option=`echo "$option" | sed -e "1s/=.*//;q"` ;;
+            esac
+            echo "$progname: option $bq$option$eq requires argument." 1>&2
+            echo "$progname: use $bq--help$eq to list option syntax." 1>&2
+            exit 1
+           ;;
+          * ) shift ;;
         esac
-     ;;
+       ;;
     esac
     optarg_optional=
   }'
@@ -160,23 +183,31 @@ outfile=
 while : ; do
   case $# in 0) break ;; esac
   case "$1" in
+    -a | --antialias* | --a* )
+      optarg_optional=t
+      eval "$getopt"
+      aliasbits="$optarg"
+      case "$aliasbits" in
+        '' ) aliasbits=4 ;;
+      esac
+     ;;
     -D | --debug | --d* )
       debug=t
       verbose=t
       gs_quiet=
       shift
      ;;
-    -f | --force | --f* )
+    -F | --force | --forc )
       force=t
       shift
+     ;;
+    -f | --format* | --form* )
+      eval "$getopt"
+      format="$optarg"
      ;;
     -h | --help | --h* )
       echo "$usage" 1>&2
       exit 0
-     ;;
-    -i | --intermediary-format* | --i* )
-      eval "$getopt"
-      format="$optarg"
      ;;
     -m | --magnification* | --magnify* | --magstep* | --m* )
       eval "$getopt"
@@ -197,6 +228,16 @@ while : ; do
       xres="$optarg"
       yres="$optarg"
      ;;
+    -s | --size* | --s* )
+      eval "$getopt"
+      case "$optarg" in
+        *x* )
+          xsize=`echo "$optarg" | sed 's/x.*//'`
+          ysize=`echo "$optarg" | sed 's/.*x//'`
+         ;;
+        * ) xsize="$optarg" ysize="$optarg" ;;
+      esac
+     ;;
     -V | --version | --vers* )
       echo "$progname version $revision"
       exit 0
@@ -206,13 +247,21 @@ while : ; do
       gs_quiet=
       shift
      ;;
-    -X | --x-resolution* | --x-r* )
+    --x-resolution* | --x-r* )
       eval "$getopt"
       xres="$optarg"
      ;;
-    -Y | --y-resolution* | --y-r* )
+    --y-resolution* | --y-r* )
       eval "$getopt"
       yres="$optarg"
+     ;;
+    -X | --x-size* | --x-s* )
+      eval "$getopt"
+      xsize="$optarg"
+     ;;
+    -Y | --y-size* | --y-s* )
+      eval "$getopt"
+      ysize="$optarg"
      ;;
     -x | --x-magnification* | --x-magnify* | --x-magstep* | --x-m* )
       eval "$getopt"
@@ -252,19 +301,59 @@ done
 case "$debug" in t ) set -x ;; esac
 case "$verbose" in '' ) exec 1> /dev/null ;; esac
 
-bcinit='scale=4
-'
+case "$#:$outfile" in
+ [01]:* ) : ;;
+ *:?* )
+   echo "$progname: Can't specify output file name when multiple input files given." 1>&2
+   exit 1
+  ;;
+esac
 
-case "$format" in
-  gif8 | gifmono | ppm | ppmraw ) : ;;
+# Build a list of supported output formats.
+gs_devices_raw=`$GS -h | sed -ne '
+                  /^Available devices:/{
+                    :l
+                    n
+                    /^[^ 	]/q
+                    p
+                    b l
+                  }'`
+gs_devices=" "`echo $gs_devices_raw`" "
+
+# Determine whether requested output format is supported.
+case "$gs_devices" in
+  *" $format "* ) : ;;
   * )
-    echo "$progname: unknown intermediary format $bq$format$eq." 1>&2
-    exit 1
+    case "$format" in
+      jpg ) format=jpeg ;;
+      # If desired image format is gif, see if ppmraw or ppm (in that order)
+      # is supported by gs, and use that instead.
+      gif | gif8 | gifmono )
+        case "$gs_devices" in
+          *" ppmraw "* ) ppmtogifp=t; format=ppmraw ;;
+          *" ppm "* )    ppmtogifp=t; format=ppm ;;
+          * )
+            echo "$progname: $GS does not have gif or ppm drivers installed." 1>&2
+           ;;
+        esac
+       ;;
+    esac
+
+    # Try again to see if modified format name is supported as a gs device.
+    case "$gs_devices" in
+      *" $format "* ) : ;;
+      * )
+        exec 1>&2
+        echo "$progname: $format: unsupported format."
+        echo "Supported formats include:"
+        echo "$gs_devices_raw"
+        exit 1
+       ;;
+    esac
    ;;
 esac
 
 file_exists_hint_given_p=
-
 for file in ${1+"$@"}; do
 
   case "$file" in
@@ -275,6 +364,11 @@ for file in ${1+"$@"}; do
      ;;
   esac
 
+  case "$outfile" in
+    '' ) outputfile= ;;
+    * )  outputfile="$outfile" ;;
+  esac
+
   basename=`echo "$file" \
              | sed -e 's/\/*$//
                        s/.*\///
@@ -283,7 +377,11 @@ for file in ${1+"$@"}; do
   case "$force" in
     t ) : ;;
     * )
-      set fnord `ls -1d "$basename"*".$format" "$basename.gif" 2> /dev/null`
+      set fnord
+      case "$ppmtogifp" in
+        t ) set ${1+"$@"} `ls -1d "$basename"*.gif "" 2> /dev/null` ;;
+      esac
+      set ${1+"$@"} `ls -1d "$basename"*".$format" "$outputfile" 2> /dev/null`
       shift
       case $# in
         0 ) : ;;
@@ -295,15 +393,15 @@ for file in ${1+"$@"}; do
             * )
               file_exists_hint_given_p=t
               sed -e "s/^/$progname: /" 1>&2 <<__EOF__
-The following files in the current directory might get overwritten
+The following files in the current directory may get overwritten
 as a result of running this program.  If desired, rename or remove
-them, or just use the $bq-f$eq ($bq--force$eq) option.
+them, or use the $bq-f$eq ($bq--force$eq) option.
 __EOF__
              ;;
           esac
 
           echo
-          ls -lsd "$basename"*".$format" "$basename.gif" 2> /dev/null
+          ls -lsd ${1+"$@"} 2> /dev/null
           echo
           continue
          ;;
@@ -336,14 +434,16 @@ __EOF__
                q
              ' "$file"`
 
+  bcinit='scale=4
+  '
   case $# in
     1 )
       echo "$progname: warning: no BoundingBox found in $bq$arg$eq" 1>&2
       # Guess.  Assume image area fits in a 8.5x11 sheet.
       llx=0
       lly=0
-      urx=`echo "$bcinit ($xres * 8.5)" | bc`
-      ury=`echo "$bcinit ($yres * 11)"  | bc`
+      urx=`echo "$bcinit ($defres * 8.5)" | bc`
+      ury=`echo "$bcinit ($defres * 11)"  | bc`
       echo "$progname: warning: guessing %%BoundingBox $llx $lly $urx $ury" 1>&2
      ;;
     * )
@@ -353,83 +453,82 @@ __EOF__
      ;;
   esac
 
-  # Some bourne shells do not allow shift to take an arg, so we can't use
-  # `shift $#' here.
-  set fnord
-  shift
-
-  xsize=`echo "$bcinit ($urx - $llx) * $xmag" \
-          | bc \
-          | sed -e 's/\..*//'`
-
-  ysize=`echo "$bcinit ($ury - $lly) * $ymag" \
-          | bc \
-          | sed -e 's/\..*//'`
-
-  xres=`echo "$bcinit ($xres * $xmag)" | bc`
-  yres=`echo "$bcinit ($yres * $ymag)" | bc`
-
-  echo $progname: "$GS" -sDEVICE=$format \
-                        -sOutputFile="$basename%03d.$format" \
-                        -g${xsize}x${ysize} \
-                        -r${xres}x${yres} \
-                        $gs_quiet "$file"
-
-  echo "$llx neg $lly neg translate" \
-   | "$GS" -sDEVICE=$format \
-           -sOutputFile="$basename%03d.$format" \
-           -g${xsize}x${ysize} \
-           -r${xres}x${yres} \
-           $gs_quiet - "$file"
-
-  set fnord `ls -1d "$basename"*".$format" 2> /dev/null`
-  shift
-
-  case $# in
-    0 )
-      echo "$progname: No $basename.$format files were created!" 1>&2
-      continue
+  case "$xsize:$ysize" in
+    : )
+      # Dividing by 1 when scale=0 insures bc result is an integer
+      xsize=`echo "($urx - $llx) * $xmag / 1" | bc`
+      ysize=`echo "($ury - $lly) * $ymag / 1" | bc`
      ;;
-    1 )
-      newname=`echo "$1" | sed -e "s/001\.$format\$/.$format/"`
-      echo $progname: mv "$1" "$newname"
-      mv "$1" "$newname"
-      set fnord "$newname"
-      shift
+    [0-9]*: )
+      xmag=`echo "$bcinit $xsize / ($urx - $llx)" | bc`
+      ymag=$xmag
+      ysize=`echo "($ury - $lly) * $ymag / 1" | bc`
+     ;;
+    :[0-9]* )
+      ymag=`echo "$bcinit $ysize / ($ury - $lly)" | bc`
+      xmag=$ymag
+      xsize=`echo "($urx - $llx) * $ymag / 1" | bc`
+     ;;
+    ?*:?* )
+      xmag=`echo "$bcinit $xsize / ($urx - $llx)" | bc`
+      ymag=`echo "$bcinit $ysize / ($ury - $lly)" | bc`
      ;;
   esac
 
-  case "$format" in
-    gif* )
-      for f in ${1+"$@"}; do
-       case "$outfile" in
-         '' ) gif=`echo "$f" | sed -e "s/\.$format\$/.gif/"` ;;
-         *  ) gif="$outfile" ;;
-       esac
+  case "$xres" in
+    '' ) xres=`echo "$bcinit ($defres * $xmag)" | bc` ;;
+  esac
 
-       case "$f" in
-         "$gif" ) : ;;
-         * )
-           echo $progname: mv "$f" "$gif"
-           mv "$f" "$gif"
-          ;;
-        esac \
-         && echo "$progname: created $gif"
+  case "$yres" in
+    '' ) yres=`echo "$bcinit ($defres * $ymag)" | bc` ;;
+  esac
+
+  case "$aliasbits" in
+    0 ) alias= ;;
+    * ) alias="-dGraphicsAlphaBits=$aliasbits -dTextAlphaBits=$aliasbits" ;;
+  esac
+
+  set fnord "$GS" -sDEVICE=$format \
+                  -sOutputFile="$basename%03d.$format" \
+                  -g${xsize}x${ysize} \
+                  -r${xres}x${yres} \
+                  $alias $gs_quiet - "$file"
+  shift
+
+  echo $progname: ${1+"$@"}
+  echo "$llx neg $lly neg translate" | ${1+"$@"}
+  exitstat=$?
+  case $exitstat in
+    0 ) : ;;
+    * ) exit $exitstat ;;
+  esac
+
+  case "$ppmtogifp" in
+    t )
+      for f in "$basename"*".$format" ; do
+        g=`echo "$f" | sed -e "s/\.$format\$/.gif/"`
+        echo "$progname: running ppmtogif on $bq$f$eq"
+        ppmtogif "$f" > "$g" \
+          && rm -f "$f" \
+          && echo "$progname: created $g"
       done
+      format=gif
      ;;
-    ppm* )
-      for f in ${1+"$@"}; do
-       case "$outfile" in
-         '' ) gif=`echo "$f" | sed -e "s/\.$format\$/.gif/"` ;;
-         *  ) gif="$outfile" ;;
-       esac
-       echo "$progname: running ppmtogif on $bq$f$eq"
-       ppmtogif "$f" > "$gif" \
-        && rm -f "$f" \
-        && echo "$progname: created $gif"
-      done
+  esac
+
+  set fnord `ls -1d "$basename"[0-9]*".$format" 2> /dev/null`
+  shift
+
+  case $# in
+    1 )
+      case "$outputfile" in
+        '' ) newname=`echo "$1" | sed -e "s/001\.$format\$/.$format/"` ;;
+        *  ) newname=$outputfile ;;
+      esac
+      echo $progname: mv "$1" "$newname"
+      mv "$1" "$newname"
      ;;
   esac
 done
 
-# pstogif ends here
+# pstoany ends here
