-E (--empty-ok): New option. -f (--file): New option.

diff --git a/sayto b/sayto
--- a/sayto
+++ b/sayto
@@ -4,7 +4,7 @@
 # Created: 1993-10-05
 # Public domain
 
-# $Id: sayto,v 1.2 1995/08/15 18:45:04 friedman Exp friedman $
+# $Id: sayto,v 1.3 1995/09/23 22:10:53 friedman Exp friedman $
 
 # Commentary:
 # Code:
@@ -17,7 +17,7 @@ eq="'"
 # Ed is the standard text editor.
 stdeditor=ed
 
-usage="Usage: $progname {options} [user] {tty}
+usage="Usage: $progname {options} [user1{:tty1}] {user2{:tty2}} {...}
 
 Options are:
 -D, --debug                  Turn on shell debugging ($bq${bq}set -x$eq$eq).
@@ -25,13 +25,69 @@ Options are:
                              The editor is specified by the environment
                              variable ${bq}$EDITOR$eq, otherwise the
                              program ${bq}$stdeditor$eq is used.
+-E, --empty-ok               Send message even if empty.
+-f, --file        FILE       Read message text from file FILE.
 -h, --help                   You're looking at it.
 -q, --quiet                  Do not print confirmation about messages sent.
 "
 
 debug=
 edit=
+empty_ok=
+infile=
 verbose=t
+
+# Usage: eval "$getopt"; value=$optarg
+# or     optarg_optional=t; eval "$getopt"; value=$optarg
+#
+# This function automatically shifts the positional args as appropriate.
+# The argument to an option is optional if the variable `optarg_optional'
+# is non-empty.  Otherwise, the argument is required and getopt will cause
+# the program to exit on an error.  optarg_optional is reset to be empty
+# after every call to getopt.  The argument (if any) is stored in the
+# variable `optarg'.
+#
+# Long option syntax is `--foo=bar' or `--foo bar'.  2nd argument
+# won't get used if first long option syntax was used.
+#
+# Note: because of broken bourne shells, using --foo=bar syntax can
+# actually screw the quoting of args that end with trailing newlines.
+# Specifically, most shells strip trailing newlines from substituted
+# output, regardless of quoting.
+getopt='
+  {
+    optarg=
+    case "$1" in
+      --*=* )
+        optarg=`echo "$1" | sed -e "1s/^[^=]*=//"`
+        shift
+       ;;
+      * )
+        case ${2+set} in
+          set )
+            optarg="$2"
+            shift
+            shift
+           ;;
+          * )
+            case "$optarg_optional" in
+              "" )
+                case "$1" in
+                  --*=* ) option=`echo "$1" | sed -e "1s/=.*//;q"` ;;
+                  * ) option="$1" ;;
+                esac
+                exec 1>&2
+                echo "$progname: option $bq$option$eq requires argument."
+                echo "$progname: use $bq--help$eq to list option syntax."
+                exit 1
+               ;;
+           esac
+         ;;
+        esac
+     ;;
+    esac
+    optarg_optional=
+  }'
 
 while : ; do
   case $# in 0) break ;; esac
@@ -40,9 +96,17 @@ while : ; do
       debug=t
       shift
      ;;
-    -e | --edit | -e* )
+    -e | --edit | -ed* )
       edit=t
       shift
+     ;;
+    -E | --empty-ok | -em* )
+      empty_ok=t
+      shift
+     ;;
+    -f | --file* | -f* )
+      eval "$getopt"
+      infile="$optarg"
      ;;
     -h | --help | --h )
       echo "$usage" 1>&2
@@ -85,74 +149,136 @@ case $# in
   0 ) echo "$usage" 1>&2; exit 1 ;;
 esac
 
-umask 077
-file="/tmp/$progname$$"
-nodelete=
-
-write=${SAYTOWRITE-write}
-
-trap 'case "$nodelete" in
-        t ) : ;;
-        * ) rm -f "$file" ;;
-      esac
-      trap "" 0 1 3 15
-      exit ${exitstat-0}
-     ' 0 1 3 15
-
-trap 'echo "[Interrupted.  No message sent.]" 1>&3
-      exitstat=130
-      exit $exitstat
-     ' 2
+case "$infile" in
+  '' ) : ;;
+  * )  exec 0< "$infile" ;;
+esac
 
 case "$verbose" in
   t ) exec 3>&1 ;;
   * ) exec 3> /dev/null ;;
 esac
 
-if (> "$file") 2> /dev/null; then
-  case "$edit" in
-    t )
-      echo "[Editing message with $bq${EDITOR-$stdeditor}$eq...]" 1>&3
-      ${EDITOR-ed} $file
-      exitstat=$?
-     ;;
-    * )
-      echo "[Enter message, ending with C-d on a new line when finished, or C-c to abort.]" 1>&3
-      cat > "$file"
-      exitstat=$?
-     ;;
-  esac
+write=${SAYTOWRITE-write}
+nodelete=t
+file="$infile"
+exitstat=0
 
-  case $exitstat in
-    0 )
-      if test -s "$file"; then
-        :
-      else
-        echo "[Sending empty message.  Hope that's ok.]" 1>&3
-      fi
+if test -t 0 ; then
+  umask 077
+  file="${TMPDIR-/tmp}/$progname$$"
+  nodelete=
 
-      if $write ${1+"$@"} < "$file"; then
-        echo "[Message sent using $bq$write$eq.]" 1>&3
-      else
-        nodelete=t
+  trap 'case "$nodelete" in
+          t ) : ;;
+          * ) rm -f "$file" ;;
+        esac
+        trap "" 0 1 3 15
+        exit ${exitstat-0}
+       ' 0 1 3 15
+
+  trap 'echo "[Interrupted.  No message sent.]" 1>&3
+        exitstat=130
+        exit $exitstat
+       ' 2
+
+  if (> "$file") 2> /dev/null; then
+    case "$edit" in
+      t )
+        echo "[Editing message with $bq${EDITOR-$stdeditor}$eq...]" 1>&3
+        ${EDITOR-$stdeditor} $file
+        exitstat=$?
+       ;;
+      * )
+        echo "[Enter message, ending with C-d on a new line when finished, or C-c to abort.]" 1>&3
+        cat > "$file"
+        exitstat=$?
+       ;;
+    esac
+
+    case "$exitstat" in
+      0 ) : ;;
+      * )
         exec 1>&2
-        echo "*** $progname: $bq$write$eq exited non-successfully."
-        echo "*** $progname: You may retrieve your message from the file $file"
-        exit 1
-      fi
-     ;;
+        echo "*** $progname: Editor exited unsuccessfully."
+        echo "*** $progname: No message sent.  Sorry."
+        exit $exitstat
+       ;;
+    esac
+  else
+    exitstat=$?
+    exec 1>&2
+    echo "*** $progname: $file: Cannot create temporary file; aborting."
+    exit $exitstat
+  fi
+fi
+
+if test -s "$file"; then
+  :
+else
+  case "$empty_ok" in
+    t ) echo "[Sending empty message.]" 1>&3 ;;
     * )
-      exec 1>&2
-      echo "*** $progname: message entry program exited non-successfully."
-      echo "*** $progname: No message sent.  Sorry."
-      exit $exitstat
+      echo "[Message is empty.  Not sending.]" 1>&3
+      exit 1
      ;;
   esac
-else
-  exitstat=$?
-  exec 1>&2
-  echo "*** $progname: Could not create temporary file $bq$file$eq; aborting."
-  exit $exitstat
 fi
+
+# If only args were in format "user tty", rewrite them to "user:tty"
+# for parsing by the mechanism below equipped to handle multiple
+# user:tty pairs.
+case "$#" in
+  2 )
+    case "$2" in
+      /dev/* | tty* | pts/* )
+        set fnord "$1:$2"
+        shift
+       ;;
+    esac
+   ;;
+esac
+
+exitstat=0
+for user in ${1+"$@"}; do
+  tty=
+  case "$user" in
+    *:* )
+      oIFS="$IFS"
+      IFS=':'
+      set fnord $user
+      IFS="$oIFS"
+      user=$2
+      tty="$3"
+
+      # The `write' program implicitly adds "/dev", so strip it out here
+      case "$tty" in
+        /dev/* ) tty=`echo "$tty" | sed -e 's/\/dev\///'` ;;
+      esac
+     ;;
+  esac
+
+  case "$tty" in
+    '' ) s="$user" ;;
+    *  ) s="$user on /dev/$tty" ;;
+  esac
+
+  if $write $user $tty < "$file" ; then
+    echo "[Message sent to $s using $bq$write$eq.]" 1>&3
+  else
+    echo "*** $progname: $bq$write$eq to $s was unsuccessful." 1>&2
+    nodelete=t
+    exitstat=1
+  fi
+done
+
+case "$exitstat:$nodelete" in
+  1:t )
+    if test -t 0; then
+      echo "*** $progname: message retained in $bq$file$eq." 1>&2
+    fi
+    exit $exitstat
+   ;;
+esac
 
 # sayto ends here
