Totally frobbed out to do version number checking before adding options.

diff --git a/wget b/wget
--- a/wget
+++ b/wget
@@ -1,38 +1,69 @@
 #!/bin/sh
 
-# $Id$
+# $Id: wget,v 1.1 2005/03/13 19:07:43 friedman Exp $
 
-wget=`run-next -p $0 || false`
+wget=`run-next -p $0 || echo false`
 
-# So many web servers out there discriminate against wget's user-agent,
+# So many web servers out there discriminate against wget's default user-agent,
 # so fabricate a different one.
-user_agent='Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.5) Gecko/20041107 Mozilla/1.2'
+user_agent='Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.7.8) Gecko/20050513 Fedora/1.0.4-1.3.1 Firefox/1.0.4'
+
+cookies=$HOME/etc/misc/.wget/cookies.txt
+
+# Get major and minor version numbers for wget
+eval `$wget --version \
+        | sed -ne '1s/^.*get \([0-9]*\)\.\([0-9]*\).*/vmajor=\1 vminor=\2/ip'`
+
+atleast() { [ $vmajor -eq $1 ] && [ $vminor -ge $2 ] || [ $vmajor -gt $1 ]; }
+
+opts="--verbose
+      --server-response
+      --timestamping
+      --wait=0
+      --tries=0
+      --cache=off
+      --passive-ftp
+      --follow-ftp
+     "
+
+if atleast 1 6; then
+  opts="$opts \
+        --html-extension
+        --page-requisites
+        --waitretry=60
+       "
+fi
+
+if atleast 1 7 && [ -f "$cookies" ]; then
+  opts="$opts
+        --cookies=on
+        --load-cookies=$cookies
+       "
+  if [ -w "$cookies" ] && [ ! -h "$cookies" ]; then
+    opts="$opts --save-cookies=$cookies"
+  fi
+fi
+
+if atleast 1 8 && [ -t 1 ]; then
+  # Use in-place progress bar if stdout is a tty
+  opts="$opts --progress=bar:force"
+fi
+
+# Add timeout and retry options to wget 1.9 and later
+if atleast 1 9; then
+  opts="$opts
+        --dns-timeout=30
+        --connect-timeout=30
+        --read-timeout=300
+
+        --retry-connrefused
+       "
+       #--dns-cache=off
+fi
 
 exec $wget \
   --user-agent="$user_agent" \
-  \
-  --verbose \
-  --progress=bar:force \
-  --server-response \
-  --timestamping \
-  \
-  --wait=0 \
-  --tries=0 \
-  --waitretry=60 \
-  \
-  --dns-timeout=30 \
-  --connect-timeout=30 \
-  --read-timeout=300 \
-  \
   --execute 'robots = off' \
-  --html-extension \
-  --cache=off \
-  \
-  --cookies=on \
-  --load-cookies=$HOME/etc/misc/.wget/cookies.txt \
-  \
-  --passive-ftp \
-  \
-  ${1+"$@"}
+  $opts "$@"
 
 # wget ends here
