Substantial modifications to use xrandr 1.4 syntax and work around vnc module bug which crashes the X server.
(get_current_parameters): New function.
(compute_new_orientation): New function.
(xrandr1): New function.
(max): New function.
(rotate): New function.

(main): Don't adjust both CTM and evdev axes.
Just adjust one or the other, preferring CTM if the pointer supports it.

diff --git a/x-rotate-display b/x-rotate-display
--- a/x-rotate-display
+++ b/x-rotate-display
@@ -1,34 +1,52 @@
 #!/bin/sh
-# $Id: rotate-display,v 1.1 2012/07/22 04:30:11 friedman Exp $
+# $Id: rotate-display,v 1.2 2012/07/22 22:36:33 friedman Exp $
 
-current_orientation()
+get_current_parameters()
 {
-    xrandr -q --verbose --screen ${1-$screen} \
-        | sed -n -e '/ connected/!d' \
-                 -e 's/.*) \([^ ][^ ]*\) (.*/\1/' \
-                 -e   's/normal/0/p' \
-                 -e     's/left/1/p' \
-                 -e 's/inverted/2/p' \
-                 -e    's/right/3/p' \
-                 -e q
+    set x `xrandr --screen 0 \
+             | sed -e '/ connected/!d' \
+                   -e 's/ (.*//' \
+                   -e 's/\([0-9]*\)x\([0-9]*\)[0-9+---]*/\1 \2/' \
+                   -e 's/ connected//' \
+                   -e q`
+
+    case $# in
+        5 ) : ;;
+        4 ) set "$@" normal ;;
+        * ) echo "Can't determine current settings properly.  Aborting." 1>&2
+            exit 1 ;;
+    esac
+    shift
+
+    output=$1 c_xres=$2 c_yres=$3
+    case $4 in
+        normal   ) c_orient=0 ;;
+        left     ) c_orient=1 ;;
+        inverted ) c_orient=2 ;;
+        right    ) c_orient=3 ;;
+    esac
 }
 
-new_orientation()
+compute_new_orientation()
 {
     case $1 in
-        0 | normal   ) echo 0 ;;
-        1 | left     ) echo 1 ;;
-        2 | inverted ) echo 2 ;;
-        3 | right    ) echo 3 ;;
+        0 | normal   ) n_orient=0 ;;
+        1 | left     ) n_orient=1 ;;
+        2 | inverted ) n_orient=2 ;;
+        3 | right    ) n_orient=3 ;;
 
-        l | lturn    ) echo $((((4 + $current_orientation) + 1) % 4)) ;;
-        r | rturn    ) echo $((((4 + $current_orientation) - 1) % 4)) ;;
+        l | lturn    ) n_orient=$((((4 + $c_orient) + 1) % 4)) ;;
+        r | rturn    ) n_orient=$((((4 + $c_orient) - 1) % 4)) ;;
+        f | flip     ) n_orient=$((((4 + $c_orient) - 2) % 4)) ;;
 
         t | *tablet )
-            case $current_orientation in
-                0 ) echo 1 ;; # normal -> left
-                * ) echo 0 ;; #    any -> normal
+            case $c_orient in
+                0 ) n_orient=1 ;; # normal -> left
+                * ) n_orient=0 ;; #    any -> normal
             esac ;;
+
+        * ) echo "$1: invalid argument" 2>&1
+            exit 1 ;;
     esac
 }
 
@@ -74,32 +92,73 @@ pointer_ids()
     xinput list | sed -ne '/ pointer /!d' -e 's/.*id=\([0-9]*\).*/\1/p'
 }
 
+xrandr1()
+{
+    xrandr --screen $screen --output $output "$@"
+}
+
+max()
+{
+    max=$1
+    shift
+    for n in "$@"; do
+        if [ $n -gt $max ]; then
+            max=$n
+        fi
+    done
+    echo $max
+}
+
+rotate()
+{
+    case $n_orient in
+        0 ) s_orient=normal   ;;
+        1 ) s_orient=left     ;;
+        2 ) s_orient=inverted ;;
+        3 ) s_orient=right    ;;
+    esac
+
+    # 2014-11-23 (still current 2015-10-04)
+    # tigervnc module will crash the X server when rotating unless the
+    # display is the same dimension on both axes.  To work around this, we
+    # temporarily change the display to be square (larger in both
+    # directions) and then set it back to its new proper size.
+    if xdpyinfo | grep -q VNC; then
+        max=`max $c_xres $c_yres`
+        xrandr1 --fb ${max}x${max} --rotate $s_orient
+
+        case $c_orient:$n_orient in
+            0:2 | 2:0 | 1:3 | 3:1 ) xrandr1 --fb ${c_xres}x${c_yres} ;;
+            *                     ) xrandr1 --fb ${c_yres}x${c_xres} ;;
+        esac
+    else
+        xrandr1 --rotate $s_orient
+    fi
+}
+
 main()
 {
     direction=${1-rturn}
     screen=${2-0}
 
-    current_orientation=`current_orientation $screen`
-        new_orientation=`new_orientation $direction`
+    get_current_parameters  $screen
+    compute_new_orientation $direction
 
-    case $new_orientation in
-        $current_orientation ) return 0 ;;
+    case $n_orient in
+        $c_orient ) return 0 ;;
     esac
 
     for id in `pointer_ids`; do
         props=`xinput list-props $id`
         case $props in
-            *'Evdev Axes Swap'* )
-                calibrate_evdev $new_orientation $id ;;
-        esac
-
-        case $props in
             *'Coordinate Transformation Matrix'* )
-                calibrate_ctm   $new_orientation $id ;;
+                 calibrate_ctm   $n_orient $id ;;
+            *'Evdev Axes Swap'* )
+                calibrate_evdev $n_orient $id ;;
         esac
     done
 
-    xrandr -o $new_orientation
+    rotate
     fancy-xearth -once &
 }
 
